import Head from "next/head";
import Navbar from "../components/Navbar";
import ShowcaseCard from "../components/ShowcaseCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>SixDesign</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div className="hero-section container">
        <div className="row row-cols-1 row-cols-md-2 align-items-center">
          <div className="col col-md-9">
            <h1 className="main-title pt-5">
              We’re a creative ‍ design agency from Canada
            </h1>
            <div className="py-2"></div>
            <button className="btn btn-lg btn-mine2 btn-trans">
              Get your quote
              <img src="/arrow.svg" alt="arrow" className="img-fluid arrow" />
            </button>
            <button className="btn btn-lg btn-trans">Browse Portfolio</button>
          </div>
          <div className="col col-md-3 d-flex flex-column gap-3 pt-2">
            <ShowcaseCard
              image="/kipling.jpg"
              imagealt="kipling station condos"
              title="Kipling Station Condos - Rego Realty"
            ></ShowcaseCard>
            <ShowcaseCard
              image="/oakpark.jpg"
              imagealt="oakpark village"
              title="The Village of Oak Park - Rego Realty"
            ></ShowcaseCard>
            <ShowcaseCard
              image="/knight.jpg"
              imagealt="Knightsbridge Condos"
              title="Knightsbridge Condos - Rego Realty"
            ></ShowcaseCard>
          </div>
        </div>
      </div>
    </>
  );
}
