import Head from "next/head";
import Navbar from "../components/Navbar";
import ShowcaseCard from "../components/ShowcaseCard";
import ServiceCard from "../components/ServiceCard";
import PortfolioCard from "../components/PortfolioCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>SixDesign</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div className="hero-section container">
        <div className="row row-cols-1 row-cols-md-2 align-items-center">
          <div className="col col-md-9">
            <div className="d-flex gap-5  pt-5">
              <div className="d-flex flex-column">
                <h5 className="fs-3 fw-bold">40+</h5>
                <p>Happy Clients</p>
                <div className="border-bottom border-2 border-dark"></div>
              </div>
              <div className="d-flex flex-column">
                <h5 className="fs-3 fw-bold">54</h5>
                <p>Projects Completed</p>
                <div className="border-bottom border-2 border-dark"></div>
              </div>
              <div className="d-flex flex-column">
                <h5 className="fs-3 fw-bold">20</h5>
                <p>Dedicated Members</p>
                <div className="border-bottom border-2 border-dark"></div>
              </div>
              <div className="d-flex flex-column">
                <h5 className="fs-3 fw-bold">10+</h5>
                <p>Recognitions</p>
                <div className="border-bottom border-2 border-dark"></div>
              </div>
            </div>
            <h1 className="main-title pt-1">
              <span class="aff2">
                We’re a creative ‍ design agency from Canada
              </span>
            </h1>
            <div className="py-2"></div>
            <button className="btn btn-lg btn-mine2 btn-trans">
              Get your quote
              <img src="/arrow.svg" alt="arrow" className="img-fluid arrow" />
            </button>
            <button className="btn btn-lg btn-trans">Browse Portfolio</button>
          </div>
          <div className="col col-md-3 d-flex flex-column gap-3 pt-2">
            <ShowcaseCard
              image="/kipling.jpg"
              imagealt="kipling station condos"
              title="Kipling Station Condos - Rego Realty"
            ></ShowcaseCard>
            <ShowcaseCard
              image="/oakpark.jpg"
              imagealt="oakpark village"
              title="The Village of Oak Park - Rego Realty"
            ></ShowcaseCard>
            <ShowcaseCard
              image="/knight.jpg"
              imagealt="Knightsbridge Condos"
              title="Knightsbridge Condos - Rego Realty"
            ></ShowcaseCard>
          </div>
        </div>
      </div>
      <div className="yc-section mt-5">
        <div className="container">
          <div className="d-flex flex-column align-items-center mb-5">
            <span className="yc-subtitle text-uppercase fw-bold">What You Get</span>
            <h2 className="yc-title">Top-Notch Services</h2>
          </div>

          <div className="row align-items-center">
            {/* Left Column: 3 Services */}
            <div className="col-md-4">
              <ServiceCard
                image="/design.svg"
                imagealt="Beautifully Designed"
                title="Beautifully Designed"
                description="Stunning designs that captivate your audience."
              />
              <ServiceCard
                image="/responsive.svg"
                imagealt="100% Responsive"
                title="100% Responsive"
                description="Optimized for all devices, ensuring seamless browsing."
              />
              <ServiceCard
                image="/animations.svg"
                imagealt="Smooth Animations"
                title="Smooth Animations"
                description="Engaging animations for an immersive experience."
              />
            </div>

            {/* Middle Column: Vertical list of all 6 titles */}
            <div className="col-md-4 yc-list-container d-none d-md-flex">
              <ul className="p-0 m-0 w-100">
                <li className="yc-list-item">Beautifully Designed</li>
                <li className="yc-list-item">100% Responsive</li>
                <li className="yc-list-item">Smooth Animations</li>
                <li className="yc-list-item">CMS Content</li>
                <li className="yc-list-item">Templates Set</li>
                <li className="yc-list-item">Friendly Support</li>
              </ul>
            </div>

            {/* Right Column: Other 3 Services */}
            <div className="col-md-4">
              <ServiceCard
                className="text-md-end"
                image="/cms.svg"
                imagealt="CMS Content"
                title="CMS Content"
                description="Easy-to-update always up-to-date content management system."
              />
              <ServiceCard
                className="text-md-end"
                image="/pack.svg"
                imagealt="Templates Set"
                title="Templates Set"
                description="Wide range of customizable templates to choose from."
              />
              <ServiceCard
                className="text-md-end"
                image="/support.svg"
                imagealt="Friendly Support"
                title="Friendly Support"
                description="Expert and responsive support team at your service."
              />
            </div>
          </div>

          {/* Two Large Images */}
          <div className="row mt-5">
            <div className="col-md-6 mb-4 mb-md-0">
              <img src="/kipling.jpg" alt="Portfolio 1" className="yc-rounded-img" />
            </div>
            <div className="col-md-6">
              <img src="/oakpark.jpg" alt="Portfolio 2" className="yc-rounded-img" />
            </div>
          </div>
        </div>
      </div>
      <div className="py-5"></div>
      <div className="yc-section pt-0">
        <div className="container">
          <div className="d-flex flex-column align-items-center mb-5">
            <span className="yc-subtitle text-uppercase fw-bold">Our Work</span>
            <h2 className="yc-title">Discover Our Creativity</h2>
          </div>
          <div className="yc-portfolio-grid">
            <PortfolioCard
              image="/kipling.jpg"
              imagealt="kipling station condos"
              title="Kipling Station Condos - Rego Realty"
            ></PortfolioCard>
            <PortfolioCard
              image="/oakpark.jpg"
              imagealt="oakpark village"
              title="The Village of Oak Park - Rego Realty"
            ></PortfolioCard>
            <PortfolioCard
              image="/knight.jpg"
              imagealt="Knightsbridge Condos"
              title="Knightsbridge Condos - Rego Realty"
            ></PortfolioCard>
          </div>
        </div>
      </div>
      <div className="py-5"></div>
      <div className="py-5"></div>
      <div className="py-5"></div>
    </>
  );
}
